### ISSUE TITLE
메모장 프로젝트 환경세팅

### ISSUE THREAD

**Issue by chessta0126** [chessta0126/memo_220919#1]
기획 -> 일정표 -> DB 설계 -> URL 설계 -> 구현 -> 테스트(QA)

## 기획
- [x] 오븐앱 회원가입
- [ ] 기획서 작성

## DB 설계 계획 (구글 스프레드 시트)
- [x] 테이블 설계 (user, post)
- [x] Url 설계 (게시판 목록, 글쓰기, 글 상세, 로그인, 회원가입)
- [x] API 설계 (글쓰기, 글 수정, 글 삭제, 로그인, 로그아웃, 회원가입, id 중복확인)

## MySQL에서 실제 DB 설계
- [x] User 테이블
- [x] Post 테이블

## STS 환경 설정
- [x] STS 설치
- [x] Marketplace에서 web tools install 설치
- [x] 인코딩 방식 설정 (UTF-8)
- [x] 프로젝트 만들기

### 2. JSON 확인 : @ResponseBody + String return
- [x] **1) MemoApplication.java의 @SpringBootApplication 위에 어노테이션 추가**
```
@EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class})
```

- [x] **2) debug 에러 해결(서버를 일단 한 번이라도 켜야 함)**
```
일단 서버 실행하고 프로젝트 우측 클릭 > Run As > Run Configurations > Arguments 탭 첫번째에 문구 추가
--debug
```

- [x] **3) main에 TestController 클래스 만들기 + @Controller**

### 3. JSP 동작 확인 : String return
- [x] **1) gradle에 dependency 추가**
```
implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
implementation group: 'org.glassfish.web', name: 'jakarta.servlet.jsp.jstl', version: '2.0.0'
```
-> gradle refresh

- [x] **2) application.properties 파일 삭제 후 application.yml 추가(먼저 읽힘)**
-> new -> file -> application.yml (탭 정렬 맞추기)
```
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
```

- [x] **3) src> main> webapp> WEB-INF> jsp 폴더 만들기**

### 4. DB 연동 확인 : 어노테이션 제거, DB 설정 java, yml 접속정보 추가, config, logback.xml

- [x] **1) MemoApplication.java의 @SpringBootApplication 위에 어노테이션 제거**
```
// @EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class})
```

- [x] **2) config (베이스 패키지 안에 config 패키지 생성)**
main에 com.memo.config 패키지 -> DatabaseConfig 클래스 만들기
```
@Configuration
@MapperScan(basePackages="com.memo.*")
public class DatabaseConfig {

 @Bean
    public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
        SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource);

        Resource[] res = new PathMatchingResourcePatternResolver().getResources("classpath:mappers/*Mapper.xml"); //  앞: 경로, *뒤: 파일 이름 이렇게 끝나야 함
        sessionFactory.setMapperLocations(res);

        return sessionFactory.getObject();
    }
}
```

- [x] **3) logback - 쿼리 수행 로그 세팅**
src/main/resources -> logback-spring.xml에 아래 코드 복붙
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">

    <!-- Appenders -->
    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <Pattern>%d %5p [%c] %m%n</Pattern>
        </encoder>
    </appender>

    <!-- Logger -->
    <logger name="★베이스패키지★" level="DEBUG" appender-ref="console" />

    <!-- Root Logger -->
    <root level="info">
        <appender-ref ref="console" />
    </root>
</configuration>
```

- [x] **4) yml 정보 최종 (탭 정렬이 안 맞으면 읽을 수 없으므로 주의)**
```
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:★DB 포트번호★/★DB명★?★타임존 제거★characterEncoding=UTF-8
    username: root
    password: root ★DB 비밀번호★
```

- [x] **5) postMapper.xml 생성**

### 형상 관리
- [x] repository 만들기
- [x] sourcetree를 통해 github 연동
- [x] develop, master 브랜치 생성
- [x] 커밋 & push
- [x] 크롬 웹스토어 -> zenhub 검색 & 다운로드
